version: '3.2'
services:

  userservice-app:
   image: ayushiiii/mybooks:userservice
   restart: always
   network_mode: host
   ports:
     - 7878:7878
   expose:
     - 7878
   depends_on:
     - books-mysql
     
  favouriteservice-app:
   image: ayushiiii/mybooks:favouriteservice
   restart: always
   network_mode: host
   ports:
     - 9898:9898
   expose:
     - 9898
   depends_on:
     - books-mysql

  books-mysql:
   image: mysql:5.5
   network_mode: host
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: books
     
  angular-app:
    image: ayushiiii/mybooks:angular
    build: MyBooksUI/
    network_mode: host
    container_name: angularapp-docker
    ports:
      - 4200:4200
